# Generated by Django 5.0.2 on 2024-03-02 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('DONE', 'Done'), ('IN_PROGRESS', 'in progress'), ('DRAFT', 'draft')], default='DRAFT', max_length=11)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
